//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46602050/.
        /// </summary>
        internal static string FaceBookAccountID {
            get {
                return ResourceManager.GetString("FaceBookAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://graph.facebook.com/v2.4/act_.
        /// </summary>
        internal static string FaceBookBaseURLService {
            get {
                return ResourceManager.GetString("FaceBookBaseURLService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customaudiences?.
        /// </summary>
        internal static string GetTargetAudiecne {
            get {
                return ResourceManager.GetString("GetTargetAudiecne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customaudiences.
        /// </summary>
        internal static string SaveTargetAudience {
            get {
                return ResourceManager.GetString("SaveTargetAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAAF9ZC6PZBVZCABAGF6Ow4kFjMenDWSJhd6bpoyTScxOjq2To6BO4iWHpoOZA5ASZAhpZCvf3lXnxtaReCEpul5Bi8pgT1TGziHcfomjes5FuZBDRdqj9pxY6fHAf3MB8dN6YcURLZANO1O1UtWIb7szWN2rl3aYFHvFcWDsaEGJTufgC5e5Q8aTvHQ5bXZChFhzGnTRT8V4ix2cUmsu70IMXJM1Ij1iNcXIZD.
        /// </summary>
        internal static string TokenID {
            get {
                return ResourceManager.GetString("TokenID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access_token=CAAF9ZC6PZBVZCABAGF6Ow4kFjMenDWSJhd6bpoyTScxOjq2To6BO4iWHpoOZA5ASZAhpZCvf3lXnxtaReCEpul5Bi8pgT1TGziHcfomjes5FuZBDRdqj9pxY6fHAf3MB8dN6YcURLZANO1O1UtWIb7szWN2rl3aYFHvFcWDsaEGJTufgC5e5Q8aTvHQ5bXZChFhzGnTRT8V4ix2cUmsu70IMXJM1Ij1iNcXIZD.
        /// </summary>
        internal static string TokenModifierAndID {
            get {
                return ResourceManager.GetString("TokenModifierAndID", resourceCulture);
            }
        }
    }
}
